config/routes.rb
Rails.application.routes.draw do
  get '/' => 'virtual_users#create'
  post '/' => 'virtual_users#create'
  get 'homepage' => 'static_pages#home'
  post 'select' => 'static_pages#select'

  resources :qa_suites do
    collection { post :import }
  end
  resources :test_cases
  resources :logs
end

app/models/qa_suite.rb
require 'date'
class QaSuite < ActiveRecord::Base
	has_many :test_cases

	def self.import(logfile)
#		script = String.new
#		file = 'C:\Sites\rails_projects\TH_QA_Dashboard\public\medium_log.txt'
#		script = 'C:\Sites\rails_projects\TH_QA_Dashboard\public\log2data.rb'
#		qa_suite_hash = `ruby #{script} #{file}`
#		suite_hash, cases_index = `ruby #{script} #{file}`
		qa_suite_hash = Hash.new
		tc_index = Array.new
		time_hash = Hash.new
		qa_suite_hash, tc_index = QaSuite.get_suite_data(logfile)
		qa_suite = QaSuite.create! qa_suite_hash
		tc_index.each do |tc|
			tc[:suite_id] = qa_suite.id
			TestCase.create! tc
		end
	end

	def self.get_suite_data(suite_logfile)
                suite_info = Hash.new
                pass_number = 0
                failed_number = 0
                tc_info_index = Array.new
                times_hash = Hash.new
                summary_begin_or_not = false
                suite_logs = String.new
                suite_summary = String.new
                suite_info[:log_file] = suite_logfile
                suite_info[:version], suite_info[:platform], suite_info[:suite_name], suite_info[:branch], suite_info[:build_type] = QaSuite.pre_parse_logfile(suite_logfile)
                File.open(suite_logfile, "r") do |file|
                        while line = file.gets
                                if summary_begin_or_not
                                        if line =~ /^FAILED.+file:.+/ or line =~ /^QA_WARNING\s+file:/ or line =~ /^DIFF\s+file:.+/
                                                suite_logs << line[/.projs00.+/] + ','
                                                suite_summary << line.gsub(/file:.+/, '<Pre><a href="http://sjorhqa128-1:8000/' + line[/file:.+/] + '.html">File</a><pre>')
                                        else
                                                suite_summary << line
                                        end
                                end
                                if not line =~ /^$/
                                        if line =~ /.+\sTESTCASE\s.+/
                                                c_info = Hash.new
                                                c_info[:case_name] = line[/.projs00.+/].split('/')[-1]
                                                c_info[:group] = line[/.projs00.+/].split('/')[-2]
                                                c_info[:suite_name], c_info[:branch] = suite_info[:suite_name], suite_info[:branch]
                                                c_info[:s_time] = QaSuite.parse_time(line[/^.+[0-9]{2}:[0-9]{2}/])
                                                c_info[:host] = line[/sjo[a-zA-Z]+[0-9]+\W[0-9]+/]
                                                c_info[:qa_log_path] = line[/.projs00.+/].gsub(/.pyt/, '/run.log')
                                                c_info[:path_exist_or_not] = File.exist?(c_info[:qa_log_path])
                                                c_info[:status] = 'Passed'
                                                tc_info_index << c_info
                                                pass_number += 1
                                        elsif line =~ /^FAILED\s+file.+/ or line =~ /^QA_WARNING\s+file:.+/ or line =~ /^DIFF\s+file:.+/
                                                #c_info = Hash.new
                                                #n_info = Hash.new
                                                #if n_info = tc_info_index.find {|x| x[:case_name] == line[/.projs00.+/].split('/')[-1].gsub(/.log/, '')}
                                                #       c_info[:s_time] = n_info[:s_time]
                                                #end
                                                if tc_info_index.find {|x| x[:case_name] == line[/.projs00.+/].split('/')[-1].split('.')[0] + '.pyt'}
                                                        if tc_info_index.find {|x| x[:case_name] == line[/.projs00.+/].split('/')[-1].split('.')[0] + '.pyt'}[:status] == 'Passed'
                                                                tc_info_index.find {|x| x[:case_name] == line[/.projs00.+/].split('/')[-1].split('.')[0] + '.pyt'}[:status]='Failed'
                                                                failed_number += 1
                                                        end
                                                end
                                        elsif line =~/^\s+[0-9]+\W[0-9]{2}.+/
                                                times_hash[line.split('/')[-1].split('.')[0..-2].join('.') + '.pyt'] = line.split('.')[0].strip.to_i + 1
                                        elsif line =~ /^START\sTIME+/
                                                suite_info[:start_time] = QaSuite.strp_time(line[/[0-9]{2}.+$/])
                                                suite_info[:date] = Date.today.to_s
                                        elsif line =~ /^PID.+/
                                                suite_info[:pid] = line[/[0-9]+/]
                                        elsif line =~ /^DISPLAY.+/
                                                suite_info[:display] = line[/sjoth.+/]
                                        elsif line =~ /^HOST.+/
                                                suite_info[:host] = line[/sjo.+/]
                                        elsif line =~ /^EXECUTABLE.+/
                                                suite_info[:executable] = line[/\Wprojs00.+/]
                                        elsif line =~ /^COMMAND\sLINE.+/
                                                suite_info[:command_line] = line[/\W{2}runqa.+/]
                                        elsif line =~ /^SUMMARY.+/
                                                if line =~ /.+UH\sOH.+/
                                                        suite_info[:status] = 'Failed'
                                                else
                                                        suite_info[:status] = 'Passed'
                                                end
                                        elsif line =~ /^TOTAL\sRUN.+/
                                                summary_begin_or_not = true
                                                suite_summary << line
                                        end
                                end
                        end
                        suite_info[:pass_number] = pass_number - failed_number
                        suite_info[:failed_numnber] = failed_number
                end
                suite_info[:summary] = suite_summary
                suite_info[:failed_info] = suite_logs
                tc_info_index.each do |h|
                        if not h[:s_time].nil? and not times_hash[h[:case_name]].nil?
                                h[:e_time] = h[:s_time] + times_hash[h[:case_name]].seconds
                        end
                end
                return suite_info, tc_info_index
	end

		def self.parse_time(string)
                return DateTime.parse(string)
        end

        def self.strp_time(string)
                return DateTime.strptime(string,'%m/%d/%y %H:%M:%S')
                #DateTime.strptime('05/02/16 03:58:26','%m/%d/%y %H:%M:%S')
        end

        def self.pre_parse_logfile(logfile)
                return String.new(logfile).split('/')[5].downcase, String.new(logfile).split('/')[4], String.new(logfile).split('/')[-2], String.new(logfile).split('/')[6],
 String.new(logfile).split('/')[-5]
        end

        def self.homepage_qa_suites_today(version, platform, timestamp)
                if timestamp.nil?
                        QaSuite.where("date = ?", Date.today.to_s).where("version = ?", version.downcase).where("platform = ?", platform)
                else
                        QaSuite.where("date = ?", timestamp.split('T')[0]).where("version = ?", version.downcase).where("platform = ?", platform)
                end
        end

        def self.homepage_qa_suites_by_branch(version, platform, branch)
                        QaSuite.where("version = ?", version.downcase).where("platform = ?", platform).where("branch = ?", branch)
        end

        def self.homepage_qa_suites_today_rhel5
                QaSuite.where("date = ?", Date.today.to_s).where("platform = ?", "linux_x86_64_rhel5")
        end

        def self.homepage_qa_suites_yesterday
                QaSuite.where("date = ?", Date.today.prev_day.to_s).where("platform = ?", "linux_x86_64_rhel6")
        end

        def self.homepage_qa_suites_yesterday_rhel5
                QaSuite.where("date = ?", Date.today.prev_day.to_s).where("platform = ?", "linux_x86_64_rhel5")
        end
        def rm_UTC (tstr)
           return 'N/A' if tstr == nil
           return tstr.to_s.sub(/ UTC/, '')
        end

end

app/controllers/qa_suites_controller.rb
class QaSuitesController < ApplicationController
	def new
		@qa_suite = QaSuite.new
	end

	def show
		@qa_suite = QaSuite.find(params[:id])
		@test_cases = TestCase.where("suite_id = ?", params[:id])
	end

	def index
	 	@qa_suites = QaSuite.paginate(page: params[:page],:per_page => 4)
	end

	def import
		QaSuite.import(params[:file]) 
	 	redirect_to qa_suites_url, notice: "Log file imported."
	end 
end

app/helpers/qa_suites_helper.rb
module QaSuitesHelper
	def parse_time(string)
		return DateTime.parse(string)
	end

	def strp_time(string)
		return DateTime.strptime(string,'%m/%d/%y %H:%M:%S')
	end

	def pre_parse_logfile(logfile)
		return String.new(logfile).split('/')[5], String.new(logfile).split('/')[-3]
	end

	def get_suite_data(suite_logfile)
		suite_info = Hash.new
		cases_info_index = Array.new
		suite_info[:suite_name], suite_info[:branch] = pre_parse_logfile(suite_logfile)
		File.open(suite_logfile, "r") do |file|
			while line = file.gets
				if not line =~ /^$/
					if line =~ /.+\sTESTCASE\s.+/
						c_info = Hash.new
						c_info[:case_name] = line[/.projs00.+/].split('/')[-1].gsub(/.pyt/, '')
						c_info[:group] = line[/.projs00.+/].split('/')[-2]
						c_info[:suite_name], c_info[:branch] = suite_info[:suite_name], suite_info[:branch]
						c_info[:start_time] = parse_time(line[/^.+[0-9]{2}:[0-9]{2}/])
						c_info[:host] = line[/sjo[a-zA-Z]+[0-9]+\W[0-9]+/]					
						c_info[:qa_log_path] = line[/.projs00.+/].gsub(/.pyt/, '.log') #need
						c_info[:status] = 'Passed'
						cases_info_index << c_info
					elsif line =~ /^FAILED.+file.+/
						c_info = Hash.new
						c_info[:case_name] = line[/.projs00.+/].split('/')[-1].gsub(/.log/, '')
						c_info[:group] = line[/.projs00.+/].split('/')[-2]
						c_info[:suite_name], c_info[:branch] = suite_info[:suite_name], suite_info[:branch]
#						c_info[:start_time] = parse_time(line[/^.+[0-9]{2}:[0-9]{2}/])
#						c_info[:host] = line[/sjo[a-zA-Z]+[0-9]+\W[0-9]+/]
						c_info[:status] = 'Failed'					
						c_info[:qa_log_path] = line[/.projs00.+/]
					elsif line =~ /^START\sTIME+/
						suite_info[:start_time]	= strp_time(line[/[0-9]{2}.+$/])
					elsif line =~ /^PID.+/
						suite_info[:pid] = line[/[0-9]+/]
					elsif line =~ /^DISPLAY.+/
						suite_info[:dispaly] = line[/sjoth.+/]
					elsif line =~ /^HOST.+/
						suite_info[:host] = line[/sjo.+/]
					elsif line =~ /^EXECUTABLE.+/
						suite_info[:executable] = line[/\Wprojs00.+/]
					elsif line =~ /^COMMAND\sLINE.+/
						suite_info[:command_line] = line[/\W{2}runqa.+/]
					end
					suite_info[:pass_number] = 20
					suite_info[:failed_numnber] = 1
				end
			end
		end
		return suite_info
	end
end

app/views/qa_suites/_qa_suite.html.erb
                    <tr>
                      <th style="width: 80px"><%= qa_suite.suite_name %></th>
                      <th style="width: 40px"><%= qa_suite.branch  %></th>
                      <th style="width: 40px"><%= qa_suite.build_type  %></th>
                      <th style="width: 60px"><%= qa_suite.start_time  %></th>
                      <th style="width: 60px"><%= qa_suite.end_time  %></th>
                      <th style="width: 40px">
                        <% if qa_suite.failed_numnber != 0 %>
                          <span>
                            <%= link_to "Passed", qa_suite_path(qa_suite.id), class: "btn btn-danger" %>
                          </span>
                        <% elsif %>
                          <span>
                            <%= link_to "Failed", qa_suite_path(qa_suite.id), class: "btn btn-success" %>
                          </span>
                        <% end %>
                      </th>
                      <th style="width: 20px"><%= qa_suite.pass_number %></th>
                      <th style="width: 20px"><%= qa_suite.failed_numnber %></th>
                    </tr>

app/views/qa_suites/_test_case.html.erb
                    <tr>
                      <th style="width: 20px"><% test_case.case_name %></th>
                      <th style="width: 20px"><% test_case.branch %></th>
                      <th style="width: 20px"><% test_case.group %></th>
                      <th style="width: 20px"><% test_case.host %></th>
                      <th style="width: 30px"><% test_case.s_time %></th>
                      <th style="width: 30px"><% test_case.e_time %></th>
                      <th style="width: 30px"><% test_case.status %></th>
                      <th style="width: 20px">
                        <%= link_to "Log File", test_case.qa_log_path %>
                      </th>
                    </tr>

app/views/qa_suites/index.html.erb
<% provide(:title, 'Suites') %>

          <div class="row">
            <div class="col-md-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Regression Results</h3>
                </div><!-- /.box-header -->
                <div class="box-body no-padding">
                  <table class="table table-striped">
                    <tr>
                      <th style="width: 80px">Suite Name</th>
                      <th style="width: 40px">Branch</th>
                      <th style="width: 40px">Type</th>
                      <th style="width: 60px">Start Time</th>
                      <th style="width: 60px">End Time</th>
                      <th style="width: 40px">Status</th>
                      <th style="width: 20px">Passed</th>
                      <th style="width: 20px">Failed</th>
                    </tr>
                    <%= render @qa_suites %>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            <%= will_paginate %> 
            </div><!-- /.col -->
          </div><!-- /.row -->
<%= form_tag import_qa_suites_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<%= form_tag import_qa_suites_path, multipart: true do %>
  <%= text_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/qa_suites/show.html.erb
<% provide(:title, 'Suites Detail') %>

          <div class="row">
            <div class="col-md-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Suite Detail</h3>
                </div><!-- /.box-header -->
                <div class="box-body no-padding">
                  <table class="table table-striped">
                    <tr>
                      <th style="width: 30px">Suite Name</th>
                      <th style="width: 20px">Branch</th>
                      <th style="width: 20px">Type</th>
                      <th style="width: 30px">Start Time</th>
                      <th style="width: 30px">End Time</th>
                      <th style="width: 20px">Host</th>
                      <th style="width: 20px">Display</th>
                      <th style="width: 20px">Pid</th>
                      <th style="width: 20px">Log File Path</th>
                    </tr>
                    <tr>
                      <th style="width: 30px"><%= @qa_suite.suite_name %></th>
                      <th style="width: 20px"><%= @qa_suite.branch %></th>
                      <th style="width: 20px"><%= @qa_suite.build_type %></th>
                      <th style="width: 30px"><%= @qa_suite.start_time %></th>
                      <th style="width: 30px"><%= @qa_suite.end_time %></th>
                      <th style="width: 20px"><%= @qa_suite.host %></th>
                      <th style="width: 20px"><%= @qa_suite.display %></th>
                      <th style="width: 20px"><%= @qa_suite.pid %></th>
                      <th style="width: 20px">
                        <span>
                         <%= link_to "Log File", @qa_suite.log_file %>
                      </span>
                      </th>
                    </tr>
                  </table>
                  <table class="table table-striped">
                    <tr>
                      <th style="width: 60px">Command Line</th>
                      <th style="width: 60px">Executable</th>
                    </tr>
                    <tr>
                      <th style="width: 30px"><%= @qa_suite.command_line %></th>
                      <th style="width: 30px"><%= @qa_suite.executable %></th>
                    </tr>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->

           <div class="row">
            <div class="col-md-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">TestCases Detail</h3>
                </div><!-- /.box-header -->
                <div class="box-body no-padding">
                  <table class="table table-striped">
                    <tr>
                      <th style="width: 30px">Case Name</th>
                      <th style="width: 30px">Branch</th>
                      <th style="width: 30px">Group</th>
                      <th style="width: 30px">Host</th>
                      <th style="width: 30px">Start Time</th>
                      <th style="width: 30px">End Time</th>
                      <th style="width: 30px">Status</th>
                      <th style="width: 30px">Log Path</th>
                    </tr>
                  <%= render @test_cases %>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box --> 
            </div><!-- /.col -->
          </div><!-- /.row -->